[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@bananapus/core=lib/nana-core/src",
    "@uniswap/v3-core=lib/v3-core/contracts",
    "@uniswap/permit2=lib/permit2",
    "@prb/math=lib/prb-math",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options