[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@bananapus/core=lib/nana-core/src",
    "@uniswap/v3-core=lib/v3-core/contracts",
    "@uniswap/v3-core-patched=lib/v3-core-patched",
    "@uniswap/v3-periphery-flattened=lib/v3-periphery-flattened",
    "@uniswap/permit2=lib/permit2",
    "@prb/math=lib/prb-math",
]
# Required to avoid stack too deep for invoking INonfungiblePositionManager.position() as per https://github.com/Uniswap/v3-periphery/issues/273
optimizer_runs=1000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options