[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@bananapus/core-v5/=lib/nana-core/",
    "@sphinx-labs/contracts/=lib/nana-core/lib/sphinx/packages/contracts/contracts/foundry/",
    "@bananapus/permission-ids/=node_modules/@bananapus/permission-ids/",
    "@bananapus/permission-ids-v5/=node_modules/@bananapus/permission-ids/",
    "@uniswap/v3-core=lib/v3-core/contracts",
    "@uniswap/v3-core-patched=lib/v3-core-patched",
    "@uniswap/v3-periphery-flattened=lib/v3-periphery-flattened",
    "@uniswap/permit2=lib/permit2",
    "@prb/math=lib/prb-math",
]
# Required to avoid stack too deep for invoking INonfungiblePositionManager.position() as per https://github.com/Uniswap/v3-periphery/issues/273
optimizer_runs=1000
via_ir=true

fs_permissions = [{ access = "read-write", path = "./"}]

[fuzz]
runs = 1024

[rpc_endpoints]
ethereum = "${RPC_ETHEREUM_MAINNET}"
optimism = "${RPC_OPTIMISM_MAINNET}"
base = "${RPC_BASE_MAINNET}"
arbitrum = "${RPC_ARBITRUM_MAINNET}"
ethereum_sepolia = "${RPC_ETHEREUM_SEPOLIA}"
optimism_sepolia = "${RPC_OPTIMISM_SEPOLIA}"
base_sepolia = "${RPC_BASE_SEPOLIA}"
arbitrum_sepolia = "${RPC_ARBITRUM_SEPOLIA}"
celo = "${RPC_CELO_MAINNET}"
celo_sepolia = "${RPC_CELO_SEPOLIA}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options